language: node_js

env:
  global:
      - GH_REF: github.com/me10zyl/blog.git
      - secure: "Ry79+LyMvOIb6U8vl+Nw5H6g8eq4d3UfQ9yBMgE4ZdXtfBwDixCrXKWlCpvfvzBnO9ibYoPPYqimgLPi62bVoShLf5rwkEjrx3pzdOCpTSjOxFwtMpSl7kS6epbwf8nx5HQkM4tP0mJ3uMwlqXZTeliWLzF6nswmUfY4oeoQlirqIw1xgnHifcnmaD9k402rXoIZy7QkJH1BfrEgmNjbK6mdVKDpZ/tlyTcPNr8OG90JLfkinX79Jf6ILPNaiXow7i5P7z3jN6mwjVFKciC0aP3AlviWs0dwg/Rh/nHeq7Pz6DSnV4WqQO5gCWe58QKCvhzR70tL+EkSVXmBKXYeJ6E2sxw8Vw6xjPX9K0tNxi4M6bPIEwnnq279y1xyZsusFwsoocmHTL5cy1w/lbdcXIIC/PR4OTBi8IInmuYBxaya9J7HnJvIc3kVZmtjUq34hkjenoda33IkvPBgCW5tWgj07zHvFLNUe7UwU8n192GtCszK0aVmf9QBG68qfCIen5Lx/dAutOWf6U8xFzBm1giI55tSgcNAnKgpakeBQCIkL1ozhufDXziQp+ow+0uXYXKyYAZDZag9ubTXSM2if0U+NgJY2/ataLLY7h7WctJEgTpw9kO1Rl3nu72ZLY9yKIm77DPzZZyIo2aflWVVE22n2XYr5YjKIgdw2Hj9QxY="

node_js:
  - "node"

install:
  - npm install

before_script:
  - npm install gulp

script:
  - gulp

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
