language: node_js

env:
  global:
      - GH_PAGES_REPO: me10zyl/me10zyl.github.io.git

node_js:
  - "node"

before_install:
  - rm -rf node_modules/

install:
  - npm install

before_script:
  - npm install gulp

script:
  - gulp

deploy:
  name: me10zyl
  email: me10zyl@qq.com
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  target_branch: master
  local_dir: dist
  fqdn: www.zengyilun.com
  repo: $GH_PAGES_REPO
  on:
    branch: master
