# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Essay: /essays
  # Drafts: /drafts
  Tags: /tags
  # Categories: /categories
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  search: true
  fancybox: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

reward:
  enable: false
  qrCode:
    wechat: /image/reward/wechat.png
    alipay: /image/reward/alipay.png

# ===========================================
# Social links Settings
# ===========================================
social:
  email: me10zyl@qq.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github:
  weibo:
  zhihu:
  pocket:

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 5d142d59d006582dbacd580c9eb430f5
# Google Analytics
google_analytics:

# Duoshuo
# duoshuo_shortname:
# Disqus
disqus_shortname: allyn
# netease
# netease_key: fbd74a3b14b54e05aebb88de37369614

# ===========================================
# Version
# ===========================================
version: 2.4.x

jiathis: true

breadcrum:
  archives: 归档
  essays: 随笔
  tags: 标签
  about: 关于
